### ISSUE TITLE
App stopped loading blocks at block 3652

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-prototype#17]
I closed the app and restarted and it continued to update blocks, then the error kept appearing after every 1000-1500 blocks and I eventually kept restarting until it finished updating.

Here is the error message:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/Library/Python/2.7/site-packages/socketio/virtsocket.py", line 403, in _receiver_loop
    retval = pkt_ns.process_packet(pkt)
  File "/Library/Python/2.7/site-packages/socketio/namespace.py", line 155, in process_packet
    return self.process_event(packet)
  File "/Library/Python/2.7/site-packages/flask_socketio/__init__.py", line 64, in process_event
    return self.socketio._dispatch_message(app, self, message, args)
  File "/Library/Python/2.7/site-packages/flask_socketio/__init__.py", line 137, in _dispatch_message
    ret = self.messages[namespace.ns_name][message](*args)
  File "app.py", line 286, in ping
    address = "%s:%s" % (peer[0][0], peer[0][1])
IndexError: string index out of range
<Greenlet at 0x110fc8cd0: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0x110f52210>>> failed with IndexError

**Comment by y0ssa** [comment]
Any thoughts on this? I'm trying to get up and running and stuck on 15885/30368 - have tried restarting a number of times but no dice.
